FROM ruby:2.3.7-alpine

RUN apk add --update --no-cache \
    alpine-sdk \
    postgresql-dev \
    nodejs \
    unzip \
    ghostscript \
    bash \
    supervisor \
    ffmpeg \
    exiftool \
    imagemagick \
    python-dev \
    py2-pip \
    tzdata \
    openjdk8 \
    libreoffice \
    tree

RUN mkdir -p /opt/fits && \
    curl -fSL -o /opt/fits-1.0.5.zip http://projects.iq.harvard.edu/files/fits/files/fits-1.0.5.zip && \
    cd /opt && unzip fits-1.0.5.zip && \
    chmod +X fits-1.0.5/fits.sh

RUN mkdir /data
WORKDIR /data

ADD Gemfile /data/Gemfile
ADD Gemfile.lock /data/Gemfile.lock

RUN rm -rf /var/cache/apk/*

RUN bundle install
